### PR TITLE
WIP: Add initial dialyzer workflow file

### PR DESCRIPTION
**Pull request by Rytis-Lebedys**
Add initial file to claim issue #20

### CODE REVIEW

**Comment by NobbZ** [comment]
I've added `WIP:` prefix to the title as a reminder that its a "work in progress" and not yet ready for review.

If you feel done edit the title and remove the "WIP:" prefix.

For questions inbetween just comment. I look at my GitHub at least twice a day.

**Comment by NobbZ** [comment]
@Rytis-Lebedys when do you plan to continue working on this?

I'm feeling forced to close in roughly 2 days and tag as `invalid` if there is no progress, to give other people the opportunity to tackle this.

**Comment by Rytis-Lebedys** [comment]
I am working on this right now. Do you have any ideas how could I test it?

**Comment by Rytis-Lebedys** [comment]
Compilation seems to be working.

Can you elaborate about `dialyzer` action? What should it test and what is the expected output?

**Comment by NobbZ** [comment]
As I have missed to prepare the makefile for dialyzer, and currently I'm not even sure if I already use specs in the code, I think I'll prepare for that one myself and merge your workflow for now.

Thank you for the effort you put into this!

**Pull request merged**
